'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class requestpage

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResponse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCheckSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCheckSum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRequest As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TXT_requesttype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_requesttype As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_merchantcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_merchantcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_MerchantTxnRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_MerchantTxnRefNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_ITC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_ITC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Amount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_Currencycode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Currencycode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_uniqueCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_uniqueCustomerID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_returnURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_returnURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_StoSreturnURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_StoSreturnURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_TPSLTXNID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_TPSLTXNID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_Shoppingcartdetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Shoppingcartdetails As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_TxnDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_TxnDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_mobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_mobileNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_Bankcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Bankcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_customerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_customerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trProprty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trProprty As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TXT_propertyPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_propertyPath As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_CardHolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_CardHolderName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_CardNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_CardNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_ExpiryMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_ExpiryMonth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_ExpiryYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_ExpiryYear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_CVV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_CVV As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trCardId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCardId As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TXT_CardID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_CardID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trMMID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trMMID As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TXT_MMID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_MMID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trRegisteredMobileNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRegisteredMobileNumber As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TXT_RegisteredMobileNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_RegisteredMobileNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trOTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOTP As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TXT_OTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_OTP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trKey As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TXT_IsKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_IsKey As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trIv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trIv As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TXT_IsIv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_IsIv As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTN_Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Submit As Global.System.Web.UI.WebControls.Button
End Class
