'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default7

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblhsfullname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsfullname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsfullname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsfullname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhslastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhslastname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthslastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthslastname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsemailid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsemailid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsemailid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsemailid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsmobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsmobile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsmobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsmobile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsplotno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsplotno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsplotno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsplotno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsadressone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsadressone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsadressone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsadressone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsadresstwo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsadresstwo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsadresstwo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsadresstwo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhscountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhscountry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLEnquiry_Country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEnquiry_Country As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblhsstate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsstate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlstate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlstate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblhsheadquater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsheadquater As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLCITY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLCITY As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblhssubarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhssubarea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlsubcity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlsubcity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblhsdivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsdivision As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddldivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddldivision As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblhscnf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhscnf As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthscnf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthscnf As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhstherapatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhstherapatic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddltherapatic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddltherapatic As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblhspincode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhspincode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthspincode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthspincode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhstelephone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhstelephone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthstelephone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthstelephone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsfax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsfax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsfax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsfax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsgstprovisionalid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsgstprovisionalid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsgstprovisionalid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsgstprovisionalid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhspan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhspan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthspan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthspan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsspocname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsspocname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsspocname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsspocname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsspocmobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsspocmobile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsspocmobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsspocmobile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsssistatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsssistatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsssistatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsssistatus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhsdruglicenceno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhsdruglicenceno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthsdruglicenceno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthsdruglicenceno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblhszone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhszone As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthszone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthszone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnedit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnedit As Global.System.Web.UI.WebControls.Button
End Class
