'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SortDoctors

    '''<summary>
    '''DdlBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlBranch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DdlInstitute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlInstitute As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DdlDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlDepartment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DdlSpeciality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlSpeciality As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''GVBranchDoctors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVBranchDoctors As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GVInstituteDoctors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVInstituteDoctors As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GVDeptDoctors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVDeptDoctors As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GVSpecilisationDoctors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVSpecilisationDoctors As Global.System.Web.UI.WebControls.GridView
End Class
