'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class edit_board_menbers

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''LblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DoctorCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DoctorCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EmailId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVEmailID As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''Salutation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Salutation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DoctorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DoctorName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Age As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVAGE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVAGE As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rblstgen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblstgen As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''RBLstSur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBLstSur As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''LBBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBBranch As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''RFVBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVBranch As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''DDlBG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDlBG As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtQualification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQualification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ImgPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgPhoto As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBSpecialities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBSpecialities As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''LBDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBDepartments As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''LBInstitutes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBInstitutes As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''CheckInstituteDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckInstituteDepartment As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlState As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Zip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Zip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVZip As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''PAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlPCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPState As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPCity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVPZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVPZip As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ResPh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResPh As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVResph control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVResph As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''MobPh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobPh As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVMobph control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVMobph As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''TxtHosPh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHosPh As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVHosPh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVHosPh As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''TxtHosPhExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHosPhExt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVHosPhExt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVHosPhExt As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''BillingServiceCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BillingServiceCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''JoinDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JoinDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''Passport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Passport As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Pan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Insurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Insurance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MaxPatients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaxPatients As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVMaxPat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVMaxPat As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''FUPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUPhoto As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''txtProfilePath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProfilePath As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUProfile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''Txtbriefprofile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbriefprofile As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''Txtpresentposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtpresentposition As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''TxtQualifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQualifications As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtsepcialtraining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsepcialtraining As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtexperience control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtexperience As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtexpertise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtexpertise As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtachievements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtachievements As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtpublications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpublications As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtawardsandhonours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtawardsandhonours As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtacademicexposure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacademicexposure As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txttalkdelivered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttalkdelivered As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtothers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtothers As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtmedia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmedia As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtmetades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmetades As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtmetakeyword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmetakeyword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtmetatitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmetatitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MondayTimmings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayTimmings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TuesdayTimmings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayTimmings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''WednesdayTimmings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayTimmings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ThursdayTimmings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayTimmings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FridayTimmings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayTimmings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SaturdayTimmings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayTimmings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SundayTimmings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayTimmings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdateDoctors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateDoctors As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RFVDoctorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVDoctorName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''LblDocPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDocPhoto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblProfile As Global.System.Web.UI.WebControls.Label
End Class
