'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace KimsHospitals

    Partial Public Class Admin_NAdmin_NewsnEvents_AddNews

        '''<summary>
        '''LblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TxtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RFVTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''TxtDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''RFVDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''CalendarExtender1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''FUNewsImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FUNewsImage As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''RFVImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVImage As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''DDLNewsPapers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLNewsPapers As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ObjDSNewsPapers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSNewsPapers As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''RFVNewsPaper control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVNewsPaper As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''TxtEdition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtEdition As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RFVEdition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVEdition As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''TxtPageNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtPageNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TxtLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtLanguage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RFVLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVLanguage As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''LBBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LBBranch As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''DDLBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLBranch As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ObjDSBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSBranch As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''RFVBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVBranch As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''DDLSpecialisation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLSpecialisation As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ObjDSSpecialisation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSSpecialisation As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''FUPDF control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FUPDF As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''BtnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ValidationSummary2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary2 As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''GVPrintNews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GVPrintNews As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ObjDSNews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSNews As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
