'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace KimsHospitals

    Partial Public Class Admin_Miscellaneous_ManageEvents

        '''<summary>
        '''LblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''EventTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''REVAllName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents REVAllName As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''RFVAllianceName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVAllianceName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''EventDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''CalendarExtender1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''RFVEventDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVEventDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''TxtEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtEndDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Image2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image2 As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''CalendarExtender2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CalendarExtender2 As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''RFVEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVEndDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''TxtVenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtVenue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''RFVVenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVVenue As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''DDLBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLBranch As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''RFVBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVBranch As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ObjDSBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSBranch As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''DDLSpec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLSpec As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''RFVSpecialisation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVSpecialisation As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ObjDSpecialisation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSpecialisation As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''ddlEventGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEventGroup As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''RFVEventGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RFVEventGroup As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''EventPDF control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventPDF As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''EventDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventDesc As Global.FredCK.FCKeditorV2.FCKeditor

        '''<summary>
        '''AddEvent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddEvent As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''BtnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnCancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ValidationSummary1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''GridView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ObDSEvents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObDSEvents As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
