'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace KimsHospitals

    Partial Public Class Admin_NAdmin_NewsnEvents_ManagePrintMedia

        '''<summary>
        '''LblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TxtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TxtDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''CalendarExtender1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''DDLNewsPaper control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLNewsPaper As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DDLEdition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLEdition As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DDLLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLLanguage As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DDLPrintBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLPrintBranch As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DDLPrintSpec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DDLPrintSpec As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ObjDSPrintSpecialisation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSPrintSpecialisation As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''BtnPrintGo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnPrintGo As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ObjDSEdition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSEdition As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''ObjDSLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSLanguage As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''ObjDsNewsPapers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDsNewsPapers As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''ObjDSBranch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSBranch As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''ObjDSSpecialisation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSSpecialisation As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''ObjDSPrintBranches control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSPrintBranches As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''GVPrintNews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GVPrintNews As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ObjDSNews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSNews As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
