'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default6

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''LblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Photo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Photo As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''EmailId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVEmailID As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''RFVEmailId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVEmailId As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtfirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtlastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtpassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtreenterpassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtreenterpassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DoctorCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DoctorCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Salutation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Salutation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Age As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLBG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLBG As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtQualification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQualification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Zip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Zip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVZip As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''MobPh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobPh As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVMobph control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVMobph As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''LBBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBBranch As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''LBSpecialities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBSpecialities As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''Txtbriefprofile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbriefprofile As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''Txtpresentprofile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtpresentprofile As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''TxtQualifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtQualifications As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtsepcialtraining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsepcialtraining As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtexperience control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtexperience As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtexpertise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtexpertise As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtachievements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtachievements As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtpublications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpublications As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtawardsandhonours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtawardsandhonours As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtacademicexposure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtacademicexposure As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txttalkdelivered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttalkdelivered As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtothers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtothers As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''txtmedia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmedia As Global.FredCK.FCKeditorV2.FCKeditor

    '''<summary>
    '''AddDoctors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddDoctors As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
End Class
